channel_in: 1
channels_out: 1
kernel_chain: !!python/object/apply:numpy._core.multiarray._reconstruct
  args:
  - !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 5
  - !!python/object/apply:numpy.dtype
    args:
    - i8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - false
  - !!binary |
    OAAAAAAAAABgAAAAAAAAAIgAAAAAAAAAsAAAAAAAAADYAAAAAAAAAA==
kernel_size: 3
lr: 0.00021763716310291566
optimizer: adamw
scheduler: none
